-- =============================================================================
-- ESQUEMA Y DATA SEMILLA PARA SUPABASE - HYPER ENCUESTAS / SGF C.C. HIPER JUMBO
-- =============================================================================

-- 1. TABLA: leads (Prospectos comerciales C.C. Hiper Jumbo)
CREATE TABLE IF NOT EXISTS public.leads (
    id VARCHAR(50) PRIMARY KEY,
    nombre TEXT NOT NULL,
    zona TEXT NOT NULL,
    cat TEXT NOT NULL,
    prov TEXT NOT NULL,
    pago NUMERIC DEFAULT 0,
    pts INT DEFAULT 0,
    score VARCHAR(10) NOT NULL,
    plan TEXT NOT NULL,
    feas TEXT NOT NULL,
    accion TEXT NOT NULL,
    avatar VARCHAR(10) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABLA: map_locals (Geometría del plano interactivo y asignación de vendedores)
CREATE TABLE IF NOT EXISTS public.map_locals (
    id VARCHAR(50) PRIMARY KEY,
    x NUMERIC NOT NULL,
    y NUMERIC NOT NULL,
    w NUMERIC NOT NULL,
    h NUMERIC NOT NULL,
    nombre TEXT NOT NULL,
    score VARCHAR(10) NOT NULL,
    vendedor TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABLA: survey_responses (Registro de Encuestas y Visitas Comerciales de Campo)
CREATE TABLE IF NOT EXISTS public.survey_responses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    local_id VARCHAR(50) NOT NULL,
    nombre_local TEXT,
    zona TEXT,
    vendedor TEXT,
    visit_result TEXT NOT NULL,
    motivo_no_realizada TEXT,
    observaciones_visita TEXT,
    prov_actual TEXT,
    velocidad TEXT,
    pago_mensual TEXT,
    verificado_factura BOOLEAN DEFAULT FALSE,
    satisfaccion INT,
    fallas TEXT[],
    impacto TEXT,
    plan_sgf TEXT,
    redes_sociales TEXT,
    sistema_facturacion TEXT,
    pagos_automatizados TEXT,
    interes_automatizar TEXT,
    contacto_nombre TEXT,
    contacto_tel TEXT,
    contacto_email TEXT,
    rol_decision TEXT,
    horario_atencion TEXT,
    mejor_horario_visita TEXT,
    notas_cierre TEXT,
    canal TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- HABILITAR ROW LEVEL SECURITY (RLS)
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.map_locals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.survey_responses ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS RLS: Lectura y escritura pública (Anon Key) + Gestión Admin
DROP POLICY IF EXISTS "Permitir lectura publica de leads" ON public.leads;
CREATE POLICY "Permitir lectura publica de leads" ON public.leads FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir edicion publica de leads" ON public.leads;
CREATE POLICY "Permitir edicion publica de leads" ON public.leads FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir lectura publica de mapa" ON public.map_locals;
CREATE POLICY "Permitir lectura publica de mapa" ON public.map_locals FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir lectura y creacion publica de encuestas" ON public.survey_responses;
CREATE POLICY "Permitir lectura y creacion publica de encuestas" ON public.survey_responses FOR ALL USING (true) WITH CHECK (true);


-- =============================================================================
-- DATA SEMILLA REAL C.C. HIPER JUMBO (INSERTS ESTÁTICOS)
-- =============================================================================

-- Inserción de Prospectos (Leads)
-- ACTUALIZACIÓN DE TODOS LOS 180+ LOCALES REALES DE C.C. HIPER JUMBO EN SUPABASE
INSERT INTO public.leads (id, nombre, zona, cat, prov, pago, pts, score, plan, feas, accion, avatar) VALUES
('ED01', 'ESTACIONAMIENTO', 'PLANTA BAJA', 'Estacionamiento', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'ES'),
('ESOT01', 'ESTACIONAMIENTO', 'SOTANO', 'Estacionamiento', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'ES'),
('FCK01', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Area Rentable', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FCK02', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Area Rentable', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC01', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC01A', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC01B', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC02', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC03', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC03A', 'Joanes Lunch, C. A.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'JL'),
('FC04A', 'Express Hong Kong, C. A.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'EH'),
('FC04B', 'Grill Mania, C. A.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'GM'),
('FC05', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC06', 'PIZZA MIA, C.A', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'PM'),
('FC07', 'Inversiones Jumbo Foods, C. A.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'IJ'),
('FC08', 'Sazón Express, C. A.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'SE'),
('FC09', 'QUIMI 2511, C.A.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'Q2'),
('FC10', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC11', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC12', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC13', 'MELENDEZ RUIZ INVERSIONES, C.A.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'MR'),
('FC14', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC15', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC16', 'Art Look MF CA', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'AL'),
('FC18', 'Kilaimin Jumbo, C. A.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'KJ'),
('FC19', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC20', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC21', 'Inversiones Sumo, C. A.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'IS'),
('FC22', 'Inversiones Sumo, C. A.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'IS'),
('FC23', 'Shawarma Corner', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'SC'),
('FC24', 'L''Artigian, ca.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'LA'),
('FC25', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC26', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC27', 'Art Look MF CA', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'AL'),
('FC28', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC29', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('FC30', 'Inversiones 0220, c.a.', 'FERIA DE COMIDA', 'Local Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAA', 'Inversiones Charbel 2020, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'IC'),
('PAB', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAC', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAD', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAE', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAF', 'Rec Mundial, C.A', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'RM'),
('PAG', 'Solutec Gamer', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'SG'),
('PAH', 'Academia de Formacion Integral Youcandance Perez', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 85, 82, 'A2', '300 Mbps PYME', 'Factible', 'Seguimiento comercial', 'AF'),
('PAI', 'Upalu, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'UP'),
('PAJ', 'Fantasy´ Pink, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'FP'),
('PAK', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAL', 'Inversiones 24666, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'I2'),
('PAM', 'Inversiones 24666, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'I2'),
('PAEK01', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAEK02', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAEK03', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAEK04', 'Nova Electronic. C.A', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'NE'),
('PAEK05', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAEK05A', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAEK06', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAEK07', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAEK08', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAEK09', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAEK10', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAEK11', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAEK12', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PAEK13', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PANK01', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA01', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA02', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA03', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA04', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA05', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA06', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA07', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA08', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA09', 'inversiones 0220 c,a,', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA10', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA11', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA12', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA13', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA14', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA15', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA16', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA17', 'The Cigar World, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'TC'),
('PA18', 'A & V SPA Y ESTUDIO, C.A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'VS'),
('PA19', 'Inversiones Kasozz, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'IK'),
('PA20', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA21', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA22', 'ME AMO COMO SOY, C.A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'MA'),
('PA23', 'LOTUS BEAUTY STUDIO, C.A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'LB'),
('PA24', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA25', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA26', 'WOMAN FIT', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'WF'),
('PA27', 'Platinum Empire, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'PE'),
('PAN', 'Inversiones 24666, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'I2'),
('PAÑ', 'Inversiones 24666, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'I2'),
('PA30', 'Lokuras Fashion, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'LF'),
('PA31', 'Lokuras Fashion, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'LF'),
('PA32', 'Lokuras Fashion, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'LF'),
('PA33', 'Aston for Men, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'AF'),
('PA34', 'Aston for Men, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'AF'),
('PA35', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA36', 'MAKEUPS KR, C.A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'MK'),
('PA37', 'G Q Store Jean´s, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'GQ'),
('PA38', 'G Q Store Jean´s, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'GQ'),
('PA39', 'TU PUNTO SHOP ELECTRONIC III', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'TP'),
('PA40', 'L@RD COMPANY, C.A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'LC'),
('PA41', 'Inversiones Coraplus C.A', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'IC'),
('PA42', 'Inversiones Coraplus C.A', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'IC'),
('PA43', 'Chipper Extremos Reload, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'CE'),
('PA44', 'El Punto de la Belleza 6792, C.A', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'EP'),
('PA45', 'BIENES RAICES DISCOVERY, C.A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'BR'),
('PA46', 'BIENES RAICES DISCOVERY, C.A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'BR'),
('PA47', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 82, 'A2', '300 Mbps PYME', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA48', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 82, 'A2', '300 Mbps PYME', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA49', 'Grupo B. L., C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 85, 82, 'A2', '300 Mbps PYME', 'Factible', 'Seguimiento comercial', 'GB'),
('PA50', 'Casino Platinum, C.A', 'PLANTA ALTA', 'Local Casino', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'CP'),
('PA51', 'Casino Platinum, C.A', 'PLANTA ALTA', 'Local Casino', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'CP'),
('PA52', 'AZAD BOUTIQUE, C.A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'AB'),
('PA53', 'KP ZONA DIGITAL, C.A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'KZ'),
('PA54', 'KIDS BARBERSHOP RC 2024, C.A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'KB'),
('PA55', 'Carpinteria Ribaez, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'CR'),
('PA56', 'Inv.Manco y Medina', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 85, 82, 'A2', '300 Mbps PYME', 'Factible', 'Seguimiento comercial', 'IM'),
('PA56A', 'Sal y Brasas Steak House, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 85, 82, 'A2', '300 Mbps PYME', 'Factible', 'Seguimiento comercial', 'SB'),
('PA56B', 'Sal y Brasas Steak House, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 85, 82, 'A2', '300 Mbps PYME', 'Factible', 'Seguimiento comercial', 'SB'),
('PA57', 'Sal y Brasas Steak House, C. A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 85, 82, 'A2', '300 Mbps PYME', 'Factible', 'Seguimiento comercial', 'SB'),
('PA58', 'TOGET MCY, C.A', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'TM'),
('PA59', 'TOGET MCY, C.A', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'TM'),
('PA60', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA61', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA62', 'VENEZIA JOYAS VIP, C.A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'VJ'),
('PA63', 'VENEZIA JOYAS VIP, C.A.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'VJ'),
('PA64', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA65', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA66', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA67', 'Datro Cloting, C.A', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'DC'),
('PA68', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PA69', 'Dream Big Store C.A', 'PLANTA ALTA', 'Local Pa', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'DB'),
('PA70', 'Compañía Anonima Empresa Cines Unidos, C. A.', 'PLANTA ALTA', 'Local Cine', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'CA'),
('PA70A', 'Compañía Anonima Empresa Cines Unidos, C. A.', 'PLANTA ALTA', 'Local Cine', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'CA'),
('PBEK01', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PBEK02', 'JHEISON JESUS MENA MACHADO', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'JJ'),
('PBEK03', 'SATRIM', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'SA'),
('PBNK01', 'MOBILE SHOP LAS AMERICAS, C.A.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'MS'),
('PBNK01A', 'MOBILE SHOP LAS AMERICAS, C.A.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'MS'),
('PBNK02', 'TIRO D´ESKINA, C.A.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'TD'),
('PBNK03', 'TIRO D´ESKINA, C.A.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'TD'),
('PBNK04', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PBNK05', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PBNK06', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PBNK07', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PBNK07A', 'BARCHICOA 1, C.A.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'B1'),
('PBNK07B', 'inversiones criollo ferrer, c.a.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'IC'),
('PBNK08', 'Corporac.Logica Digital CA', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'CD'),
('PBNK09', 'COMERCIALIZADORA DOGS MDA, C.A.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'CD'),
('PBOK01', 'Creativy Space C.A.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'CS'),
('PBOK01A', 'Inversiones Modelo J & M C.A.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'IM'),
('PBOK02', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PBOK03', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PBOK04', 'Macoba cafe C. A.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'MC'),
('PBOS01', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PBOS02', 'Hyper Joyas, C. A.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'HJ'),
('PBPEK01', 'EZ ACCESORIOS GALERIA, C.A.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'EA'),
('PBPEK02', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PBPEK03', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PBPEK04', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PBPEK05', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PBPEK06', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Kiosco Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PB01', 'MARACAY BEER COMPANY, C.A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 85, 82, 'A2', '300 Mbps PYME', 'Factible', 'Seguimiento comercial', 'MB'),
('PB02', 'Lentes Centro Occidente, C. A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'LC'),
('PB03', 'Xtasis Store, C,A', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'XS'),
('PB04', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PB05', 'INVERSIONES PARAISO INTIMO, C.A', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'IP'),
('PB06', 'Hyper 412, C.A', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'H4'),
('PB07', 'Calzados Paurit II, C. A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'CP'),
('PB08', 'Opti - Color #2, C. A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'OC'),
('PB08A', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PB09', 'Friday´s Proyect, C. A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'FP'),
('PB10', 'INVERSIONES 140965, C.A', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'I1'),
('PB11', 'INVERSIONES 140965, C.A', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'I1'),
('PB12', 'Dayenu Computers & Electronics, C.A', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'DC'),
('PB13', 'Dayenu Computers & Electronics, C.A', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'DC'),
('PB14', 'HIPER BABY KING, C.A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'HB'),
('PB15', 'Baklava Pastry', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'BP'),
('PB16', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PB17', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PB18', 'FARMACIA MALANGA C.A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 85, 82, 'A2', '300 Mbps PYME', 'Factible', 'Seguimiento comercial', 'FM'),
('PB19', 'Rattan Home, C.A', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'RH'),
('PB20', 'Rattan Home, C.A', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'RH'),
('PB21', 'Rattan Home, C.A', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'RH'),
('PB22', 'Plus Optica, C. A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'PO'),
('PB23', 'La Tintoreria, C. A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'LT'),
('PB24', 'Perfumería Ciudad Jardín, C. A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'PC'),
('PB25', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PB26', 'STUDIO 97, C.A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'S9'),
('PB27', 'atp tecnology', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'AT'),
('PB28', 'atp tecnology', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'AT'),
('PB29', 'KATTY PAREDES SPA & ESTETICA, C.A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'KP'),
('PB30', 'Amore Fashion Concept, C.A', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'AF'),
('PB31', 'CGG, C. A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'CG'),
('PB32', 'CGG, C. A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'CG'),
('PB33', '+Cotas Shop, C. A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'CS'),
('PB34', '+Cotas Shop, C. A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'CS'),
('PB35', 'Liss Authentic, C..A', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'LA'),
('PB36', 'G & V SPA CAFFE C.A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'GV'),
('PB37', 'Viajes y Turismo Hyperglobe, C. A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'VT'),
('PB38', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PB39', 'IKOA BRAND CORP, C.A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'IB'),
('PB40', 'dark pink', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'DP'),
('PB41', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PB42', 'Adrenalina 826, C. A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'A8'),
('PB43', 'Adrenalina 826, C. A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'A8'),
('PB44', 'inversiones 0220, c.a.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 0, 82, 'A2', '300 Mbps PYME', 'Pendiente', 'Disponible para prospección', 'I0'),
('PB45', 'Inversiones 0220, c.a.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 0, 82, 'A2', '300 Mbps PYME', 'Pendiente', 'Disponible para prospección', 'I0'),
('PB46', 'MUEBLES RUBINOVA', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'MR'),
('PB47', 'MUEBLES RUBINOVA', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'MR'),
('PB48', 'C. E. T.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'ET'),
('PB49', 'Inversiones JPL.C,A', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'IJ'),
('PB50', 'SISPROT GLOBAL FIBER', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 0, 100, 'A1', '200 Mbps PYME', 'Factible', '✅ Oficina / Punto SGF', 'SG'),
('PB50A', 'SISPROT GLOBAL FIBER', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 0, 100, 'A1', '200 Mbps PYME', 'Factible', '✅ Oficina / Punto SGF', 'SG'),
('PB51', 'SISPROT GLOBAL FIBER', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 0, 100, 'A1', '200 Mbps PYME', 'Factible', '✅ Oficina / Punto SGF', 'SG'),
('PB52', 'SISPROT GLOBAL FIBER', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 0, 100, 'A1', '200 Mbps PYME', 'Factible', '✅ Oficina / Punto SGF', 'SG'),
('PB53', 'By Sendy Romero Studio, c.a', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'BS'),
('PB54', 'IVCA DISTRIBUIDORA, C.A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'ID'),
('PB55', 'INVERSIONES ERNAS 2021, C.A.', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'IE'),
('PB56', 'Inversiones y Rest. Mardan, c.a (Churromania)', 'PLANTA BAJA', 'Local Pb', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'IR'),
('PB57', 'Hyper Mercado Modelo, C. A.', 'PLANTA BAJA', 'Local Mercado', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'HM'),
('PCUK01', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PCUK02', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PCUK03', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PCUK04', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PCUK05', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PCUK06', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PCUK07', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PFCK01', 'inversiones 0220 c.a.', 'FERIA DE COMIDA', 'Kiosco Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PFCK02', 'inversiones 0220 c.a.', 'FERIA DE COMIDA', 'Kiosco Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PFCK03', 'inversiones 0220c.a.', 'FERIA DE COMIDA', 'Kiosco Feria', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('PHBK01', 'Fit Life Store, C.A', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'FL'),
('PHBK02', 'Fit Life Store, C.A', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'FL'),
('PHBK03', 'Fit Life Store, C.A', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'Factible', 'Seguimiento comercial', 'FL'),
('PHBK04', 'Inversiones 0220, c.a.', 'PLANTA ALTA', 'Kiosco Pa', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('SOT01', 'Inversiones 0220, c.a. OFICINAS', 'SOTANO', 'Oficinas', 'Por Encuestar', 85, 82, 'A2', '300 Mbps PYME', 'Factible', 'Seguimiento comercial', 'I0'),
('SOT02', 'Inversiones 0220, c.a. OFICINAS', 'SOTANO', 'Oficinas', 'Por Encuestar', 85, 82, 'A2', '300 Mbps PYME', 'Factible', 'Seguimiento comercial', 'I0'),
('SOT02A', 'Inversiones 0220, c.a.', 'SOTANO', 'Oficinas', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('SOT03', 'Inversiones 0220, c.a.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('SOT04', 'Inversiones 0220, c.a.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('SOT05', 'Inversiones 0220, c.a.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('SOT06', 'Inversiones 0220, c.a.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('SOT07', 'CITYMAX ELECTRONICS, C.A', 'SOTANO', 'Local Sotano', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'CE'),
('SOT08', 'Inversiones 0220, c.a.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('SOT08A', 'Perfumeria Ciudad Jardin, C.A', 'SOTANO', 'Deposito', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'No Factible', 'Seguimiento comercial', 'PC'),
('SOT09', 'STUDIO 97, C.A.', 'SOTANO', 'Deposito', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'No Factible', 'Seguimiento comercial', 'S9'),
('SOT10', 'Centro Escuela de Sistemas e Informatica, C. A.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'CE'),
('SOT11', 'RMK STORE, C.A.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'RS'),
('SOT12', 'ENGLISH WITH CECILIA', 'SOTANO', 'Local Sotano', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'EW'),
('SOT13', 'ENGLISH WITH CECILIA', 'SOTANO', 'Local Sotano', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'EW'),
('SOT14', 'MAJO STUDIOS', 'SOTANO', 'Local Sotano', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'MS'),
('SOT14A', 'Parqueo, 30 SNC OFICINA', 'SOTANO', 'Oficinas', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'P3'),
('SOT15', 'Grand Le Quartz, c.a', 'SOTANO', 'Local Sotano', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'GL'),
('SOT15A', 'ELYURI ELOISA NARANJO UGARTE', 'SOTANO', 'Local Sotano', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'EE'),
('SOT16', 'ELYURI ELOISA NARANJO UGARTE', 'SOTANO', 'Local Sotano', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'EE'),
('SOT16A', 'MARACAY BEER COMPANY, C.A.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 85, 82, 'A2', '300 Mbps PYME', 'Factible', 'Seguimiento comercial', 'MB'),
('SOT17', 'Inversiones 0220, c.a.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('SOT18', 'Confecciones mc, C. A.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'CM'),
('SOT19', 'Inversiones 0220, c.a.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('SOT20', 'Inversiones 0220, c.a.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('SOT21', 'Inversiones 0220, c.a.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('SOT21A', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT21B', 'Inversiones 0220, c.a.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('SOT22', '+Cotas Services, C. A.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'CS'),
('SOT23', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT24', 'SERVICIOS FLYTELINE C.A.', 'SOTANO', 'Deposito', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'No Factible', 'Seguimiento comercial', 'SF'),
('SOT25', 'FAMILY CREAM C.A.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'FC'),
('SOT26', 'FAMILY CREAM C.A.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'FC'),
('SOT27', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT28', 'YUJ FORMACION BIENESTAR C.A.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'YF'),
('SOT29', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT29A', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT30', 'Hyper Mercado Modelo, C.A', 'SOTANO', 'Local Mercado', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'HM'),
('SOT31', 'Nova Electronics, c.a', 'SOTANO', 'Local Sotano', 'Por Encuestar', 55, 72, 'B', '200 Mbps PYME', 'Factible', 'Seguimiento comercial', 'NE'),
('SOT32', 'Hyper Gym, C. A.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'HG'),
('SOT33', 'Hyper Gym, C. A.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'HG'),
('SOT34', 'Hyper Gym, C. A.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'HG'),
('SOT35', 'Hyper Gym, C. A.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'HG'),
('SOT36', 'Hyper Gym, C. A.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'HG'),
('SOT37', 'Hyper Gym, C. A.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'HG'),
('SOT37A', 'Inversiones 0220, c.a.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 0, 25, 'D', '50 Mbps Hogar', 'Pendiente', 'Disponible para prospección', 'I0'),
('SOT38', 'Hyper Mercado Modelo, C.A', 'SOTANO', 'Local Mercado', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'HM'),
('SOT39', 'inversiones 0220, c.a.', 'SOTANO', 'Local Sotano', 'Por Encuestar', 0, 95, 'A1', '600 Mbps Emp.', 'Pendiente', 'Disponible para prospección', 'I0'),
('SOT40', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT41', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT42', 'Joanes Lunch, C.A', 'SOTANO', 'Deposito', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'No Factible', 'Seguimiento comercial', 'JL'),
('SOT43', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT44', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT45', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT46', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT47', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT48', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT49', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT50', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT51', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT52A', 'Inversiones Sumo, C.A', 'SOTANO', 'Deposito', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'No Factible', 'Seguimiento comercial', 'IS'),
('SOT52B', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT52C', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT52D', 'Sazon Express II, C.A', 'SOTANO', 'Deposito', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'No Factible', 'Seguimiento comercial', 'SE'),
('SOT52E', 'Sazon Express II, C.A', 'SOTANO', 'Deposito', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'No Factible', 'Seguimiento comercial', 'SE'),
('SOT52F', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT52G', '+ Cotas Shop, C.A', 'SOTANO', 'Deposito', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'No Factible', 'Seguimiento comercial', 'CS'),
('SOT52H', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT53', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT54', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT55', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT56', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT57', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT58', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT59', 'CROIII, C.A.', 'SOTANO', 'Deposito', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'No Factible', 'Seguimiento comercial', 'CR'),
('SOT60', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT61', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT62', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT63', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT64', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT65', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT66', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT67', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('SOT68', 'Shawarma Corner', 'SOTANO', 'Deposito', 'Por Encuestar', 35, 58, 'C', '100 Mbps PYME', 'No Factible', 'Seguimiento comercial', 'SC'),
('SOT69', 'Inversiones 0220, c.a.', 'SOTANO', 'Deposito', 'Por Encuestar', 0, 25, 'E', 'N/A', 'No Factible', 'Disponible para prospección', 'I0'),
('TR01', 'Casino Platinum, C.A', 'TERRAZA', 'Terraza', 'Por Encuestar', 210, 95, 'A1', '600 Mbps Emp.', 'Factible', 'Seguimiento comercial', 'CP'),
('TR02', 'Terraza', 'TERRAZA', 'Terraza', 'Por Encuestar', 85, 82, 'A2', '300 Mbps PYME', 'Factible', 'Seguimiento comercial', 'TE')
ON CONFLICT (id) DO UPDATE SET 
    nombre = EXCLUDED.nombre,
    zona = EXCLUDED.zona,
    cat = EXCLUDED.cat,
    pago = EXCLUDED.pago,
    pts = EXCLUDED.pts,
    score = EXCLUDED.score,
    plan = EXCLUDED.plan,
    feas = EXCLUDED.feas,
    accion = EXCLUDED.accion,
    avatar = EXCLUDED.avatar;


-- Inserción de Plano/Mapa de Locales
INSERT INTO public.map_locals (id, x, y, w, h, nombre, score, vendedor) VALUES
('PB04', 38,  72,  78, 48, 'Mobile Shop',      'A2', 'Carlos R.'),
('PB05', 124, 72,  78, 48, 'Logica Digital',   'B',  'Carlos R.'),
('PB01', 210, 72,  78, 48, 'Hyper Joyas',      'C',  'María L.'),
('PB06', 296, 72,  78, 48, 'Dogs Market',      'D',  'María L.'),
('PB02', 38,  130, 78, 48, 'Macoba Cafe',      'B',  'Carlos R.'),
('PB03', 124, 130, 78, 48, 'Tiro DEskina',     'C',  'Pedro M.'),
('PB07', 210, 130, 78, 48, 'Creativy Space',   'B',  'Pedro M.'),
('PB08', 296, 130, 78, 48, 'SATRIM Kiosco',    'C',  'Ana G.'),
('PA50', 38,  248, 100,54, 'Casino Platinum',  'A1', 'Carlos R.'),
('PA04', 148, 248, 100,54, 'Hyper Mercado',    'A1', 'Carlos R.'),
('PA07', 258, 248, 78, 54, 'Tu Punto Shop',    'A1', 'María L.'),
('PA01', 344, 248, 78, 54, 'SGF Oficina',      'A1', 'Nuestra oficina'),
('PA06', 38,  312, 78, 48, 'Lotus Beauty',     'A2', 'Pedro M.'),
('PA09', 124, 312, 78, 48, 'Farmacia Malanga', 'A2', 'María L.'),
('PA03', 210, 312, 78, 48, 'KP Zona Digital',  'B',  'Ana G.'),
('PA02', 296, 312, 78, 48, 'Lokuras Fashion',  'C',  'Ana G.'),
('FC01', 38,  432, 68, 44, 'Joanes Lunch',     'B',  'Pedro M.'),
('FC02', 114, 432, 68, 44, 'Express HK',       'B',  'Pedro M.'),
('FC04', 190, 432, 68, 44, 'Pizza Mia',        'B',  'Ana G.'),
('FC07', 266, 432, 68, 44, 'Shawarma Corner',  'C',  'Ana G.'),
('FC09', 342, 432, 68, 44, 'LArtigian',        'D',  '—'),
('FC05', 418, 432, 68, 44, 'Sazón Express',    'B',  'Carlos R.')
ON CONFLICT (id) DO UPDATE SET 
    nombre = EXCLUDED.nombre,
    score = EXCLUDED.score,
    vendedor = EXCLUDED.vendedor;

-- Registro de Encuesta Ejemplo Inicial
INSERT INTO public.survey_responses (
    local_id, nombre_local, zona, vendedor, visit_result, prov_actual, velocidad, pago_mensual,
    verificado_factura, satisfaccion, fallas, impacto, plan_sgf, contacto_nombre, contacto_tel,
    contacto_email, rol_decision, canal
) VALUES (
    'PB04', 'Mobile Shop Las Americas', 'Planta Baja', 'Carlos Ramírez', 'Completada', 'Inter', '50', '45',
    true, 2, ARRAY['Cortes frecuentes', 'Lentitud en hora pico'], 'Alto', 'PYME 300 Mbps ($44.83/mes)',
    'Ana Martínez', '+58 412-555-0198', 'ana@mobileshop.ve', 'Decisor Directo', 'WhatsApp'
);
